### ISSUE TITLE
Add OSGi support

### ISSUE THREAD

**Issue by xafero** [xafero/dynkt#3]
OSGi support would be great to embed scripting capabilities in Eclipse-based applications.

**Comment by renatoathaydes** [comment]
This is not very hard to do... it will require creating a new jar with the kotlin-compiler's jar embedded in it because the kotlin-compiler is not a OSGi bundle and probably will never be. It may be necessary to check with the kotlin team if that would be ok to do. @xafero  Do you have any contact with the kotlin team?

**Comment by xafero** [comment]
@renatoathaydes No, but the complete language and toolset are free under ASL2, so this is no concern to me. 

![dynkt-feature-in-eclipse](https://cloud.githubusercontent.com/assets/6005006/15425830/294f9312-1e8b-11e6-9208-ee31e13acb23.png)

Would you like to test? See 8c4580cf1f2d00f7feca2b9ef31a8598f08cd96e

**Comment by renatoathaydes** [comment]
Hi.

I was thinking of support for OSGi as in pure OSGi, not Eclipse.

It would just require exporting the `ScriptEngine` service with dynamic services (which you did) and most likely embedding the kotlin-compiler jar... otherwise, how you're going to invoke the kotlin compiler?

The end result should just be a single OSGi bundle...

**Comment by xafero** [comment]
Hi,

if you separate the Kotlin bundle from the engine bundle, users are able to update Kotlin to a newer version - as long as it is API-compatible (for example all 1.x), so I am trying this option.

**Comment by xafero** [comment]
I've done some work related to OSGi, so please have a look. The script engine factory can be found already.

**Comment by renatoathaydes** [comment]
not sure what to look at. Your commit messages are quite unhelpful. This kind of changes could be easy to track if you made it a pull request.

Anyway, I can try to run this in a OSGi container as long as the kotlin-compiler is available in OSGi... as the project is not a bundle and needs access to the system classpath, I'm not sure how to get that working yet... did you figure this out?

**Comment by xafero** [comment]
Check out the releases page [(v0.1-alpha)](https://github.com/xafero/dynkt/releases/tag/v0.1-alpha) and let me know if your container is ok with it. I've found a simple way to generate a single OSGi JAR which contains everything plus the script engine.

**Comment by renatoathaydes** [comment]
No, it doesn't work:

```
ERROR: Bundle com.xafero.dynkt.jsr223-osgi [26] Error starting file:/Users/renato/programming/projects/osgiaas/build/osgi/bundle/dynkt-1.0.0-SNAPSHOT.jar (org.osgi.framework.BundleException: Unable to resolve com.xafero.dynkt.jsr223-osgi [26](R 26.0): missing requirement [com.xafero.dynkt.jsr223-osgi [26](R 26.0)] osgi.wiring.package; (osgi.wiring.package=apple.awt) Unresolved requirements: [[com.xafero.dynkt.jsr223-osgi [26](R 26.0)] osgi.wiring.package; (osgi.wiring.package=apple.awt)])
org.osgi.framework.BundleException: Unable to resolve com.xafero.dynkt.jsr223-osgi [26](R 26.0): missing requirement [com.xafero.dynkt.jsr223-osgi [26](R 26.0)] osgi.wiring.package; (osgi.wiring.package=apple.awt) Unresolved requirements: [[com.xafero.dynkt.jsr223-osgi [26](R 26.0)] osgi.wiring.package; (osgi.wiring.package=apple.awt)]
    at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111)
    at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)
    at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
    at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
    at java.lang.Thread.run(Thread.java:745)

```

If you know Gradle, try this plugin to get the bundle running in a OSGi container easily:

https://github.com/renatoathaydes/osgi-run

All you need is a build file looking like this:

``` groovy
plugins {
    id "com.athaydes.osgi-run" version "1.4.3"
}

repositories {
    mavenCentral()
    flatDir {
        dirs 'libs' // put your jar in libs/
    }
}

dependencies {
    osgiRuntime name: 'dynkt-1.0.0-SNAPSHOT' // name of the jar without the extension
}
```

Save this in `build.gradle`, copy the jar into the `libs` folder, then run:

```
gradle runOsgi
```

And you get the above error (from Felix).

There's a lot of problems with the bundle you created, by the way... you are exporting ALL or the kotlin-compiler packages, when you shouldn't export any package at all. You are importing ALL of the stuff that's already in the kotlin-compiler jar, when you shouldn't import any of it (as you are embedding it). You are also importing packages that no OSGi container or bundle will give you, such as `apple.awt`, making this a completely non-portable bundle. There's even some broken imports like `com.google.common.collect.ConcurrentHashMultiset.com.google.common.collect`.

If you have little knowledge of OSGi, I suggest you don't try to continue with this because this is quite tricky to do correctly... If you can make the scriptEngine work with the latest kotlin version, I can turn the project into an OSGi bundle later. What do you think?

**Comment by xafero** [comment]
I agree with you upon the huge load of wrong dependencies. Now I can load the bundle in Felix. What are your plans to use it? I thought of something like [this](https://apache.googlesource.com/felix/+/trunk/mishell/), but sadly, it is broken.

**Comment by renatoathaydes** [comment]
I want to make Kotlin one of the languages my cli app supports: [OSGiaaS](https://github.com/renatoathaydes/osgiaas/blob/master/docs/osgiaas-cli.md).

It's not released yet, but I already support Groovy and JavaScript.
Commands (non-scripts) can be written in any JVM language that supports OSGi (Java, Kotlin, Groovy, Ceylon).

**Comment by xafero** [comment]
Interesting. Maybe have a look at [this](https://github.com/xafero/SLR/blob/master/slr/src/main/resources/scriptEngines.cfg.xml) or [that](https://github.com/xafero/vee/blob/master/vee/config.xml)... In both projects, you can reference a language by its ID and it will be loaded on demand

**Comment by renatoathaydes** [comment]
Hi @xafero . I installed the bundle you've created... great you've managed to get it installed!

But it does not run at all.

I made several changes to try to get it to work, including:
- fixed the usage of the maven-bundle-plugin to let it calculate imports/exports properly
- added `DynamicImport-Package: *` to the manifest because this is necessary for any script engine to work in OSGi.
- let the maven-bundle-plugin do the embedding of the dependencies, so it can add the correct classpath to the bundle, amongst other things.
- added metadata to export the `ScriptEngineFactory` as an OSGi service using Declarative Services. 

But then I got stuck... even though the Script can be instantiated, it can't do anything.

Calling `getScriptEngine()` causes an error:

```
gro-osgiaas> try { s.scriptEngine } catch(e) {e.printStackTrace() }
cannot extract: /org/jetbrains/kotlin/utils/PathUtil.class from bundle://22.0:4/org/jetbrains/kotlin/utils/PathUtil.class
java.lang.IllegalStateException: Resource not found: /org/jetbrains/kotlin/utils/PathUtil.class
    at org.jetbrains.kotlin.utils.PathUtil.getResourcePathForClass(PathUtil.java:138)
    at org.jetbrains.kotlin.utils.PathUtil.getPathUtilJar(PathUtil.java:130)
    at org.jetbrains.kotlin.utils.PathUtil.getKotlinPathsForCompiler(PathUtil.java:72)
    at com.xafero.dynkt.core.KotlinCompiler.<init>(KotlinCompiler.java:44)
    at com.xafero.dynkt.KotlinScriptEngine.<init>(KotlinScriptEngine.java:33)
    at com.xafero.dynkt.KotlinScriptEngineFactory.getScriptEngine(KotlinScriptEngineFactory.java:59)
```

I haven't been able to find out how to fix this.. just letting you know how I'm going here.

If you want I can make a PR with my changes, but this error must be fixed for the engine to actually do anything useful.

**Comment by xafero** [comment]
First of all, I would like to see your changes. This is tricky for me, but my analysis goes so far:

The just logged message 'cannot extract' hides the problematic method 'extractRoot' in com.intellij.openapi.application.PathManager. This manager only works on 'file:' and 'jar:' protocols, not on 'bundle'.

So, I patched it, but now comes an configuration error... META_INF/extensions/common.xml is not found :-(

**Comment by renatoathaydes** [comment]
That makes sense. In OSGi you can't just read all jars in the classpath... so code that loads resources like this (like the kotlin-compiler) are a pain to make work... If this `META-INF/extensions/common.xml` were present in the dynkt bundle, it should work fine... do you know if this file is there?

**Comment by xafero** [comment]
1. Yes, it exists in exactly the same folders and structure.
2. The PathManager has been patched to deliver the path of the OSGi JAR; this works at least if the runtime does not extract the package (like Felix after install per gogo-shell) or changes something in another way.
3. Maybe one could change the loader to use the classloader instead of opening as Zip/Jar ?

**Comment by pun-ky** [comment]
also got stuck on that issue with `PathUtil` :/

**Comment by xafero** [comment]
No updates since years.
